# Generated by Django 4.1.7 on 2023-08-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strength", models.PositiveIntegerField(default=20)),
                ("dexterity", models.PositiveIntegerField(default=20)),
                ("health", models.PositiveIntegerField(default=20)),
                ("intelligence", models.PositiveIntegerField(default=20)),
                ("charisma", models.PositiveIntegerField(default=20)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
